ui: tape
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: safari
    version: -2..latest
  - name: opera
    version: latest
  - name: ie
    version: 10..latest
  - name: iphone
    version: -2..latest
  - name: ipad
    version: -2..latest
  - name: android
    version: -2..latest